
CREATE TABLE [USUARIO] (
[usu_id] [int] IDENTITY(1,1) NOT NULL,
[usu_nome] [varchar](25) NOT NULL,
[usu_senha] [varchar](10) NOT NULL, 
[usu_status][smallint] NOT NULL, 				 -- Domínio {00 = ativo, 01 = novo, 02 = desativado}
[usu_obs] [varchar](100) NULL,
[usu_email] [varchar](30) NULL,

CONSTRAINT [USUARIO - "USU_ID"] PRIMARY KEY CLUSTERED 
	([usu_id] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
);

CREATE TABLE [CATEGORIA](
[cat_id] [int] IDENTITY(1,1) NOT NULL,
[cat_descricao] [varchar](25) NOT NULL,

CONSTRAINT [CATEGORIA - "CAT_ID"] PRIMARY KEY CLUSTERED 
	([cat_id] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

);

CREATE TABLE [PALAVRA](
[pal_id] [int] IDENTITY(1,1) NOT NULL,
[pal_palavra] [varchar](25) NOT NULL,
[pal_categoria] int NOT NULL,
[pal_dificuldade][smallint] NOT NULL, 				-- Domínio {00 = baixa, 01 = média, 02 = alta}

CONSTRAINT [PALAVRA - "PAL_ID"] PRIMARY KEY CLUSTERED 
	([pal_id] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
);

ALTER TABLE [PALAVRA]  WITH CHECK ADD  CONSTRAINT [FK_CATEGORIA - "CAT_ID"] FOREIGN KEY([pal_categoria])
REFERENCES [CATEGORIA] ([cat_id]);


CREATE TABLE [DESAFIO](
[des_id] [int] IDENTITY(1,1) NOT NULL,
[des_origem] [int] NOT NULL, 		-- (FK em USUARIO)
[des_destino] [int] NOT NULL,		-- (FK em USUARIO)
[des_palavra] [int] NOT NULL,		-- (FK em PALAVRA)
[des_status] [smallint] NOT NULL,	-- Domínio {pronto, jogando, parado, cancelado, venceu, perdeu}
[des_tempo] [bigint] NOT NULL,

CONSTRAINT [DESAFIO - "DES_ID"] PRIMARY KEY CLUSTERED 
	([des_id] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
);

ALTER TABLE [DESAFIO]  WITH CHECK ADD  CONSTRAINT [FK_DESAFIO - "DES_ORIGEM"] FOREIGN KEY([des_origem])
REFERENCES [USUARIO] ([usu_id]);


ALTER TABLE [DESAFIO]  WITH CHECK ADD  CONSTRAINT [FK_DESAFIO - "DES_DESTINO"] FOREIGN KEY([des_destino])
REFERENCES [USUARIO] ([usu_id]);


ALTER TABLE [DESAFIO]  WITH CHECK ADD  CONSTRAINT [FK_DESAFIO - "DES_PALAVRA"] FOREIGN KEY([des_palavra])
REFERENCES [PALAVRA] ([pal_id]);

CREATE TABLE [AMIGO](
[ami_id] [int] IDENTITY(1,1) NOT NULL,
[ami_usuario] [int] NOT NULL, 	-- (FK em USUARIO)
[ami_amigo][int] NOT NULL, 		-- (FK em USUARIO)

CONSTRAINT [AMIGO - "AMI_ID"] PRIMARY KEY CLUSTERED 
	([ami_id] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
);

ALTER TABLE [AMIGO]  WITH CHECK ADD  CONSTRAINT [FK_AMIGO - "AMI_USUARIO"] FOREIGN KEY([ami_usuario])
REFERENCES [USUARIO] ([usu_id]);

ALTER TABLE [AMIGO]  WITH CHECK ADD  CONSTRAINT [FK_AMIGO - "AMI_AMIGO"] FOREIGN KEY([ami_amigo])
REFERENCES [USUARIO] ([usu_id]);



