

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FORCA_BACKOFFICE
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class FORCAEntities : DbContext
{
    public FORCAEntities()
        : base("name=FORCAEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }

    public virtual DbSet<Categoria> Categoria { get; set; }

    public virtual DbSet<Palavra> Palavra { get; set; }

}

}

