
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FORCA_BACKOFFICE
{

using System;
    using System.Collections.Generic;
    
public partial class Palavra
{

    public int Id { get; set; }

    public string IDCategoria { get; set; }

    public string IDDificuldade { get; set; }

    public string Palavra1 { get; set; }

}

}
